### ISSUE TITLE
Stratux Flam Integration

### ISSUE THREAD

**Issue by KBfly** [PepperJo/stratux#2]
1. Stratux version:
2. Stratux config:

    SDR
      - [ ] single
      - [x ] dual

    GPS
      - [ ] yes
      - [ x] no
      type:

    AHRS
      - [ ] yes
      - [ x] no

    power source: PowerBank OR PowerSuppl.

    usb cable: yes

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (Raspbian)

    EFB hardware: (Raspberry Pi2 B) ...not +

4. Description of your issue:
* The v3 radio does not support FLARM at the moment since it requires a new firmware on the radio
-> that means FLAM doesn't work with this Image V3? it works with V2?
* how can i enable or disable FLAM in Settings? (in the webgui i can't find any button / switch) - the config file says "yes it's enabled" 
* many thanks for your work!

Karsten

**Comment by VirusPilot** [comment]
It is just a coincidence that this version is numbered v3 and has nothing to do with the v3 radios. In fact this latest image fully supports FLARM, I am using it right now. FLARM is always enabled but you can only see the switch if you enable the developer mode by clicking 10 times on the version number in the middle of the main stratux website.

**Comment by KBfly** [comment]
Hallo,

many thanks for your quickly answer with hints.

good landings,

Karsten

**Comment by KBfly** [comment]
...sorry, i didn't saw the entry in the stratux.conf -> here you can also enable the dev mode.
by the way: the button to en- or disable can i see only at the laptop with firefox connected to stratux.
on my tablett (nexus7 2013) i can't see this button! realy!  ...the other button yes.
but no problem, noone need this buttons during the fly.

Thank's again for your works! 

...i'll use the stratux in my C42 and VFRnav (next version support Stratux) 

good landings,

Karsten

**Comment by PepperJo** [comment]
Hi Karsten,

Try clearing your history/cookies etc. on the tablet or use incognito mode. Some of the stuff might be cached. As stated above FLARM is enabled per default to run with the V2 Radio instead of UAT ADS-B.

Cheers,
Jonas

**Comment by KBfly** [comment]
O.K.  Danke Jonas ...gibt es einen Mailkontakt? - Issues ist ja nicht richtig.
Danke!
Karsten

**Comment by PepperJo** [comment]
Klar du kannst mich unter pepperjo _at_ japf.ch erreichen.

Gruss
Jonas
