### ISSUE TITLE
XCSoar: No data (UDP ports: 4353, 10110, 4352, 2000, 23)

### ISSUE THREAD

**Issue by dgofman** [PepperJo/stratux#4]
1. Stratux version: v1.4r5 (fe12ed3bd1)
2. Stratux config:  GDL90 MSL

    SDR
      - [ ] single
      - [ X] dual

    GPS
      - [X ] yes
      - [ ] no
      type:

    AHRS
      - [X ] yes
      - [ ] no

    power source:

    usb cable:  yes

3. EFB app and version: (e.g., WingX Pro7 8.6.2)

    EFB platform: (e.g., iOS 9.2)

    EFB hardware: (e.g., iPad Mini 2)

4. Description of your issue:

I download and install the latest version of Stratux-FLARM https://github.com/PepperJo/stratux/releases/tag/v1.5b2-flarm and XCSoar 6.8. 
In Menu->Settings the "GDL90 MSL" is enabled". Now in XCSoar, I tried to add a connection to the device "Config->Devices->Edit->UDP Port (TCP Port 10110) Device: FLARM.
The result: No Data. I tried other ports the results are the same. Please, can you help me.

**Comment by VirusPilot** [comment]
Are you sure that XCSoar supports GDL90? I would usually expect glider apps to only support the FLARM-NMEA protocol.

**Comment by dgofman** [comment]
Looks like it was before. https://github.com/cyoung/stratux/issues/489

**Comment by dgofman** [comment]
I would like to get actual ADS-B traffic on XCSoar. Currently, I have to use two application XCSoar and Stratux Web Application or Avare.

**Comment by PepperJo** [comment]
I also remember XCSoar only supporting the FLARM NMEA protocol. At least from my side there are no plans to support it. Maybe you can ask the XCSoar developers if they are willing to support GDL90 since it seems to be the defacto standard now. Alternatively you can always try the old fork that you linked above.

**Comment by dgofman** [comment]
I tried an old version. Didn't work for me https://github.com/cyoung/stratux/files/826743/update-stratux-flarm-v1.2r1-1b17cb4101.sh.zip. Maybe a problem with Stratux 3? I can see one Note: The v3 radio does not support FLARM at the moment since it requires a new firmware on the radio.

https://github.com/PepperJo/stratux/releases/tag/v1.5b2-flarm

**Comment by PepperJo** [comment]
I doubt that is has anything to do with the new v3 radio except if you did buy your Stratux in the last month or so. Btw there is no Stratux 2 or 3, this is just the radio version. Anyway the version you linked supports the same radios as "my" FLARM fork does, namely up to v2. If you happen to have the new v3 radio you are out of luck in regards to FLARM, there is currently no code base that supports the new radio.

**Comment by dgofman** [comment]
I purchased August 9, 2018 from   CrewDogElectronics
<https://www.etsy.com/shop/CrewDogElectronics?utm_source=transactional&utm_medium=email&utm_campaign=convo_notifications_010170_10683759063_0_0&campaign_label=convo_notifications&utm_content=&email_sent=1533833423&euid=COWOwEwm2QjdOUpXd70trb6mfuTP&eaid=253604199679&x_eaid=99cc42fea5&link_clicked=2>.
I don't know what version on my Stratux. Did you able to integrate with
XCSoar using your Stratux?

**Comment by PepperJo** [comment]
Then you definitely do not have the v3 radio so this FLARM fork should work in general but *not* with XCSoar. I personally do not use XCSoar. Try posting a comment on the pull request you found with the old FLARM-NMEA code maybe someone there is using XCSoar. Alternatively try reaching out on stratux.slack.com.
